Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
============= RESTART: C:\Users\trng\Desktop\Prashanth\string.py =============
Hello4
Hello4
>>> 
=========== RESTART: C:\Users\trng\Desktop\Prashanth\dictonary.py ===========
{'name': 'batman', 'age': 40, 'place': 'gotham'}
The Name is batman
None
name
age
place
name batman
age 40
place gotham
{'name': 'batman', 'age': 40, 'place': 'gotham'}
No address
>>> 
=========== RESTART: C:/Users/trng/Desktop/Prashanth/functions.py ===========
Hello World
>>> 
=========== RESTART: C:/Users/trng/Desktop/Prashanth/functions.py ===========
Hello World
Hello World
Traceback (most recent call last):
  File "C:/Users/trng/Desktop/Prashanth/functions.py", line 8, in <module>
    x()
TypeError: 'NoneType' object is not callable
>>> 
=========== RESTART: C:/Users/trng/Desktop/Prashanth/functions.py ===========
Hello World
Hello World
Traceback (most recent call last):
  File "C:/Users/trng/Desktop/Prashanth/functions.py", line 8, in <module>
    x()
TypeError: 'NoneType' object is not callable
>>> 
=========== RESTART: C:/Users/trng/Desktop/Prashanth/functions.py ===========
Hello World
Hello World
Traceback (most recent call last):
  File "C:/Users/trng/Desktop/Prashanth/functions.py", line 8, in <module>
    x()
TypeError: 'NoneType' object is not callable
>>> 
=========== RESTART: C:/Users/trng/Desktop/Prashanth/functions.py ===========
Hello World
None
>>> 
=========== RESTART: C:/Users/trng/Desktop/Prashanth/functions.py ===========
Hello World
None
Hello World
Happy Sunday
>>> 
=========== RESTART: C:/Users/trng/Desktop/Prashanth/functions.py ===========
Hello World
None
Hello World
Happy Sunday
5 6
6 5
>>> 
=========== RESTART: C:/Users/trng/Desktop/Prashanth/functions.py ===========
5 6
(6, 5)
<class 'tuple'>
>>> 
=========== RESTART: C:/Users/trng/Desktop/Prashanth/functions.py ===========
1
<class 'int'>
(1,)
<class 'tuple'>
>>> 
=========== RESTART: C:/Users/trng/Desktop/Prashanth/functions.py ===========
1
<class 'int'>
(1,)
<class 'tuple'>
Hell
Happy sunday
>>> 
=========== RESTART: C:/Users/trng/Desktop/Prashanth/functions.py ===========
1
<class 'int'>
(1,)
<class 'tuple'>
Hell
Happy sunday
Traceback (most recent call last):
  File "C:/Users/trng/Desktop/Prashanth/functions.py", line 60, in <module>
    for x in enumerate(list_a):
NameError: name 'list_a' is not defined
>>> 
=========== RESTART: C:/Users/trng/Desktop/Prashanth/functions.py ===========
1
<class 'int'>
(1,)
<class 'tuple'>
Hell
Happy sunday
0
1
2
>>> 
=========== RESTART: C:/Users/trng/Desktop/Prashanth/functions.py ===========
1
<class 'int'>
(1,)
<class 'tuple'>
Hell
Happy sunday
Traceback (most recent call last):
  File "C:/Users/trng/Desktop/Prashanth/functions.py", line 61, in <module>
    print (x,y)
NameError: name 'y' is not defined
>>> 
=========== RESTART: C:/Users/trng/Desktop/Prashanth/functions.py ===========
1
<class 'int'>
(1,)
<class 'tuple'>
Hell
Happy sunday
(0, 1)
(1, 2)
(2, 3)
>>> 
=========== RESTART: C:/Users/trng/Desktop/Prashanth/functions.py ===========
1
<class 'int'>
(1,)
<class 'tuple'>
Hell
Happy sunday
(0, 1)
(1, 2)
(2, 3)
prathik 100
Durga 200
Anand 300
>>> 
======= RESTART: C:/Users/trng/Desktop/Prashanth/function_parameter.py =======
Traceback (most recent call last):
  File "C:/Users/trng/Desktop/Prashanth/function_parameter.py", line 4, in <module>
    f1()
TypeError: f1() missing 1 required positional argument: 'a'
>>> 
======= RESTART: C:/Users/trng/Desktop/Prashanth/function_parameter.py =======
1
the value of a is 1
the value of b is 99
>>> 
======= RESTART: C:/Users/trng/Desktop/Prashanth/function_parameter.py =======
1
the value of a is 1
the value of b is 2
>>> 
======= RESTART: C:/Users/trng/Desktop/Prashanth/function_parameter.py =======
1
the value of a is 1
the value of b is 2
the value of a is 1
the value of b is 99
>>> 
======= RESTART: C:/Users/trng/Desktop/Prashanth/function_parameter.py =======
the argumnets are(1, 2, 3, 4, 5, 'Hello World')
>>> 
======= RESTART: C:/Users/trng/Desktop/Prashanth/function_parameter.py =======
the argumnets are()
>>> 
======= RESTART: C:/Users/trng/Desktop/Prashanth/function_parameter.py =======
Value of a is 1
Value of b is 1
argumnets is (3, 4, 5, 6)
>>> 
======= RESTART: C:/Users/trng/Desktop/Prashanth/function_parameter.py =======
Value of a is 1
Value of b is 1
argumnets is (3, 4, 5, 6)
Value of a is 1
Value of b is 1
argumnets is (2, 3, 4, 5, 6)
>>> 
======= RESTART: C:/Users/trng/Desktop/Prashanth/function_parameter.py =======
Value of a is 1
Value of b is 1
argumnets is (3, 4, 5, 6)
Value of a is 1
Value of b is 1
argumnets is (2, 3, 4, 5, 6)
>>> 
======= RESTART: C:/Users/trng/Desktop/Prashanth/function_parameter.py =======
Value of a is 1
Value of b is 2
argumnets is (3, 4, 5, 6)
Value of a is 1
Value of b is 99
argumnets is (2, 3, 4, 5, 6)
>>> 
======= RESTART: C:/Users/trng/Desktop/Prashanth/function_parameter.py =======
#######kwargs###########
Named arguments are {}
>>> 
======= RESTART: C:/Users/trng/Desktop/Prashanth/function_parameter.py =======
#######kwargs###########
Named arguments are {}
#######kwargs###########
Named arguments are {'name': 'batmna', 'age': 25}
>>> 
======= RESTART: C:/Users/trng/Desktop/Prashanth/function_parameter.py =======
#######kwargs###########
Named arguments are {}
#######kwargs###########
Named arguments are {'name': 'batman', 'age': 25}
>>> 
======= RESTART: C:/Users/trng/Desktop/Prashanth/function_parameter.py =======
#######kwargs###########
Named arguments are {}
#######kwargs###########
Named arguments are {'name': 'batman', 'age': 25}
>>> 
======= RESTART: C:/Users/trng/Desktop/Prashanth/function_parameter.py =======
#######kwargs###########
Named arguments are {}
#######kwargs###########
Named arguments are {'name': 'batman', 'age': 25}
Value of a is 1
Value of b is 99
argumnets is (2, 3, 4, 5, 6)
Named argumnets is {'c': 99, 'g': 53, 'd': 10}
>>> 
======= RESTART: C:/Users/trng/Desktop/Prashanth/function_parameter.py =======
#######kwargs###########
Named arguments are {}
#######kwargs###########
Named arguments are {'name': 'batman', 'age': 25}
Value of a is 1
Value of b is 99
argumnets is (2, 3, 4, 5, 6)
Named argumnets is {'c': 99, 'g': 53, 'd': 10}
>>> 
======= RESTART: C:/Users/trng/Desktop/Prashanth/function_parameter.py =======
#######kwargs###########
Named arguments are {}
#######kwargs###########
Named arguments are {'name': 'batman', 'age': 25}
Value of a is 1
Value of b is 99
argumnets is (2, 3, 4, 5, 6)
Named argumnets is {'c': 99, 'g': 53, 'd': 10}
>>> 
====== RESTART: C:/Users/trng/Desktop/Prashanth/function_within_fun.py ======
F3
>>> 
====== RESTART: C:/Users/trng/Desktop/Prashanth/function_within_fun.py ======
F1
>>> 
====== RESTART: C:/Users/trng/Desktop/Prashanth/function_within_fun.py ======
F2
F1
F3
>>> 
====== RESTART: C:/Users/trng/Desktop/Prashanth/function_within_fun.py ======
F2
F1
F3
>>> 
====== RESTART: C:/Users/trng/Desktop/Prashanth/function_within_fun.py ======
F2
This is f2
>>> 
====== RESTART: C:/Users/trng/Desktop/Prashanth/function_within_fun.py ======
erasing Backup
commnad is invalid
Taking Backup
PRinting result
>>> 
====== RESTART: C:/Users/trng/Desktop/Prashanth/function_within_fun.py ======
erasing Backup
commnad is invalid
Taking Backup
PRinting result
erasing Backup
commnad is invalid
commnad is invalid
PRinting result
>>> 
====== RESTART: C:/Users/trng/Desktop/Prashanth/function_within_fun.py ======
erasing Backup
commnad is invalid
commnad is invalid
PRinting result
>>> 
============ RESTART: C:/Users/trng/Desktop/Prashanth/modules.py ============
['C:/Users/trng/Desktop/Prashanth', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\Lib\\idlelib', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\python36.zip', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\DLLs', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\site-packages']
>>> 
============ RESTART: C:/Users/trng/Desktop/Prashanth/modules.py ============
<function generate_random_name at 0x000001D4A368F2F0>
>>> 
============ RESTART: C:/Users/trng/Desktop/Prashanth/modules.py ============
<function generate_random_name at 0x0000024F68C2F2F0>
Traceback (most recent call last):
  File "C:/Users/trng/Desktop/Prashanth/modules.py", line 12, in <module>
    print (gennnames.generate_random_name)
NameError: name 'gennnames' is not defined
>>> 
============ RESTART: C:/Users/trng/Desktop/Prashanth/modules.py ============
<function generate_random_name at 0x000001CDBAB4F2F0>
Traceback (most recent call last):
  File "C:/Users/trng/Desktop/Prashanth/modules.py", line 12, in <module>
    print (gennnames.generate_random_name)
NameError: name 'gennnames' is not defined
>>> 
============ RESTART: C:/Users/trng/Desktop/Prashanth/modules.py ============
<function generate_random_name at 0x000002BB1CF5F2F0>
Traceback (most recent call last):
  File "C:/Users/trng/Desktop/Prashanth/modules.py", line 13, in <module>
    print (generate_random_name(6))
NameError: name 'generate_random_name' is not defined
>>> 
============ RESTART: C:/Users/trng/Desktop/Prashanth/modules.py ============
<function generate_random_name at 0x000001CE5A00F2F0>
Traceback (most recent call last):
  File "C:/Users/trng/Desktop/Prashanth/modules.py", line 13, in <module>
    print (gennmaes.generate_random_name(6))
NameError: name 'gennmaes' is not defined
>>> 
============ RESTART: C:/Users/trng/Desktop/Prashanth/modules.py ============
<function generate_random_name at 0x000001BEFCD6F2F0>
Traceback (most recent call last):
  File "C:/Users/trng/Desktop/Prashanth/modules.py", line 13, in <module>
    print (gennames.generate_random_name(6))
  File "C:/Users/trng/Desktop/Prashanth\gennames.py", line 7, in generate_random_name
    temp+=alpha[randint(0, len(aplha)-1)]
NameError: name 'aplha' is not defined
>>> 
============ RESTART: C:/Users/trng/Desktop/Prashanth/gennames.py ============
>>> 
============ RESTART: C:/Users/trng/Desktop/Prashanth/modules.py ============
<function generate_random_name at 0x000001AD4C6FF2F0>
cdddda
>>> 
============ RESTART: C:/Users/trng/Desktop/Prashanth/modules.py ============
<function generate_random_name at 0x0000029753A7F2F0>
ecadeb
Hel
>>> 
============ RESTART: C:/Users/trng/Desktop/Prashanth/modules.py ============
<function generate_random_name at 0x0000029A1921F2F0>
<function limit_names at 0x0000029A1921F378>
addbba
Hel
>>> 
============ RESTART: C:/Users/trng/Desktop/Prashanth/modules.py ============
<function generate_random_name at 0x000002C6FFF8F2F0>
<function limit_names at 0x000002C6FFF8F378>
bebdce
Hel
Traceback (most recent call last):
  File "C:/Users/trng/Desktop/Prashanth/modules.py", line 20, in <module>
    print (gennnames.generate_random_name(6))
NameError: name 'gennnames' is not defined
>>> 
============ RESTART: C:/Users/trng/Desktop/Prashanth/modules.py ============
<function generate_random_name at 0x0000016A1B3EF2F0>
<function limit_names at 0x0000016A1B3EF378>
bdddac
Hel
caeecb
>>> 
============ RESTART: C:/Users/trng/Desktop/Prashanth/modules.py ============
<function generate_random_name at 0x000002A8092FF2F0>
<function limit_names at 0x000002A8092FF378>
aeebbb
Hel
bcceac
HEl
>>> 
============ RESTART: C:/Users/trng/Desktop/Prashanth/modules.py ============
<function generate_random_name at 0x00000176C595F2F0>
<function limit_names at 0x00000176C595F378>
cdcceb
Hel
cdadbc
HEl
<function generate_random_name at 0x00000176C595F2F0>
<function generate_random_name at 0x00000176C595F2F0>
>>> 
============== RESTART: C:/Users/trng/Desktop/Prashanth/json.py ==============
Traceback (most recent call last):
  File "C:/Users/trng/Desktop/Prashanth/json.py", line 4, in <module>
    import json
  File "C:/Users/trng/Desktop/Prashanth\json.py", line 10, in <module>
    address : [
NameError: name 'address' is not defined
>>> 
============== RESTART: C:/Users/trng/Desktop/Prashanth/json.py ==============
{'name': b'batman', 'age': 45, 'badhabits': None, 'address': [{'type': 'home', 'pincode': 1}], 'married': False}
Traceback (most recent call last):
  File "C:/Users/trng/Desktop/Prashanth/json.py", line 4, in <module>
    import json
  File "C:/Users/trng/Desktop/Prashanth\json.py", line 19, in <module>
    prinnt(type(sample))
NameError: name 'prinnt' is not defined
>>> 
============== RESTART: C:/Users/trng/Desktop/Prashanth/json.py ==============
{'name': b'batman', 'age': 45, 'badhabits': None, 'address': [{'type': 'home', 'pincode': 1}], 'married': False}
<class 'dict'>
Traceback (most recent call last):
  File "C:/Users/trng/Desktop/Prashanth/json.py", line 4, in <module>
    import json
  File "C:/Users/trng/Desktop/Prashanth\json.py", line 21, in <module>
    data=json.dumps(sample)     #converts the python format to the string
AttributeError: module 'json' has no attribute 'dumps'
>>> 
============== RESTART: C:/Users/trng/Desktop/Prashanth/json.py ==============
{'name': b'batman', 'age': 45, 'badhabits': None, 'address': [{'type': 'home', 'pincode': 1}], 'married': False}
<class 'dict'>
Traceback (most recent call last):
  File "C:/Users/trng/Desktop/Prashanth/json.py", line 4, in <module>
    import json
  File "C:/Users/trng/Desktop/Prashanth\json.py", line 21, in <module>
    data=json.dumps(sample)     #converts the python format to the string
AttributeError: module 'json' has no attribute 'dumps'
>>> 
============== RESTART: C:/Users/trng/Desktop/Prashanth/json.py ==============
{'name': b'batman', 'age': 45, 'badhabits': None, 'address': [{'type': 'home', 'pincode': 1}], 'married': False}
<class 'dict'>
Traceback (most recent call last):
  File "C:/Users/trng/Desktop/Prashanth/json.py", line 4, in <module>
    import json
  File "C:/Users/trng/Desktop/Prashanth\json.py", line 21, in <module>
    data=json.dumps(sample)     #converts the python format to the string
AttributeError: module 'json' has no attribute 'dumps'
>>> 
============== RESTART: C:/Users/trng/Desktop/Prashanth/json.py ==============
{'name': 'batman', 'age': 45, 'badhabits': None, 'address': [{'type': 'home', 'pincode': 1}], 'married': False}
<class 'dict'>
Traceback (most recent call last):
  File "C:/Users/trng/Desktop/Prashanth/json.py", line 4, in <module>
    import json
  File "C:/Users/trng/Desktop/Prashanth\json.py", line 21, in <module>
    data=json.dumps(sample)     #converts the python format to the string
AttributeError: module 'json' has no attribute 'dumps'
>>> 
=========== RESTART: C:/Users/trng/Desktop/Prashanth/json_file.py ===========
{'name': 'batman', 'age': 45, 'badhabits': None, 'address': [{'type': 'home', 'pincode': 1}], 'married': False}
<class 'dict'>
Traceback (most recent call last):
  File "C:/Users/trng/Desktop/Prashanth/json_file.py", line 4, in <module>
    import json
  File "C:/Users/trng/Desktop/Prashanth\json.py", line 21, in <module>
    data=json.dumps(sample)     #converts the python format to the string
AttributeError: module 'json' has no attribute 'dumps'
>>> 
=========== RESTART: C:/Users/trng/Desktop/Prashanth/json_file.py ===========
{'name': 'batman', 'age': 45, 'badhabits': None, 'address': [{'type': 'home', 'pincode': 1}], 'married': False}
<class 'dict'>
Traceback (most recent call last):
  File "C:/Users/trng/Desktop/Prashanth/json_file.py", line 4, in <module>
    import json
  File "C:/Users/trng/Desktop/Prashanth\json.py", line 21, in <module>
    data=json.dumps(sample)     #converts the python format to the string
AttributeError: module 'json' has no attribute 'dumps'
>>> 
=========== RESTART: C:/Users/trng/Desktop/Prashanth/file_json.py ===========
{'name': 'batman', 'age': 45, 'badhabits': None, 'address': [{'type': 'home', 'pincode': 1}], 'married': False}
<class 'dict'>
Traceback (most recent call last):
  File "C:/Users/trng/Desktop/Prashanth/file_json.py", line 4, in <module>
    import json
  File "C:/Users/trng/Desktop/Prashanth\json.py", line 21, in <module>
    data=json.dumps(sample)     #converts the python format to the string
AttributeError: module 'json' has no attribute 'dumps'
>>> 
============== RESTART: C:/Users/trng/Desktop/Prashanth/file.py ==============
{'name': 'batman', 'age': 45, 'badhabits': None, 'address': [{'type': 'home', 'pincode': 1}], 'married': False}
<class 'dict'>
Traceback (most recent call last):
  File "C:/Users/trng/Desktop/Prashanth/file.py", line 4, in <module>
    import json
  File "C:/Users/trng/Desktop/Prashanth\json.py", line 21, in <module>
    data=json.dumps(sample)     #converts the python format to the string
AttributeError: module 'json' has no attribute 'dumps'
>>> 
============= RESTART: C:/Users/trng/Desktop/Prashanth/files.py =============
Traceback (most recent call last):
  File "C:/Users/trng/Desktop/Prashanth/files.py", line 4, in <module>
    x=open("sample.txt", "r")
FileNotFoundError: [Errno 2] No such file or directory: 'sample.txt'
>>> 
============= RESTART: C:/Users/trng/Desktop/Prashanth/files.py =============
Traceback (most recent call last):
  File "C:/Users/trng/Desktop/Prashanth/files.py", line 3, in <module>
    x=open("sample.txt", "r")
FileNotFoundError: [Errno 2] No such file or directory: 'sample.txt'
>>> 
============= RESTART: C:/Users/trng/Desktop/Prashanth/files.py =============
hello
hi
hello
hi
Traceback (most recent call last):
  File "C:/Users/trng/Desktop/Prashanth/files.py", line 14, in <module>
    data=file.readlines()
ValueError: I/O operation on closed file.
>>> 
============= RESTART: C:/Users/trng/Desktop/Prashanth/files.py =============
hello
hi
hello
hi
['hello\n', 'hi']
hello
hi
>>> 
